# Generated by Django 6.0.7 on 2026-08-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('artist', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('album', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=4)),
                ('release_year', models.DateTimeField()),
                ('lyrics_preview', models.TextField()),
            ],
        ),
    ]
