# Generated by Django 6.0.7 on 2026-08-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='release_year',
            field=models.CharField(max_length=200),
        ),
    ]
