# Generated by Django 6.0.7 on 2026-08-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('roll_no', models.IntegerField()),
                ('course', models.CharField(max_length=200)),
                ('year', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
