# Generated by Django 6.0.7 on 2026-08-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('actor', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=200)),
                ('year', models.IntegerField(max_length=4)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('runtime', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
