# Generated by Django 6.0.7 on 2026-08-05 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Netflix',
            new_name='Movie',
        ),
    ]
