# Generated by Django 6.0.7 on 2026-08-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
