# Generated by Django 6.0.7 on 2026-07-31 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('roll_number', models.IntegerField()),
                ('email', models.CharField(max_length=200)),
                ('admission_date', models.DateTimeField(verbose_name='Admission Date')),
            ],
        ),
    ]
