# Generated by Django 6.0.7 on 2026-08-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attraction', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('country', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('timing', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
    ]
